### ISSUE TITLE
"T" is slightly clipped on the right side

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#1]
Hello,

I've noticed that when the letter "T", "F", etc. is the last one in formula, then the right side of the letter appears to be slightly clipped. I have attached a screenshot (it is not only in pyscript, it is the same on my installation) to demonstrate the issue.

![image](https://user-images.githubusercontent.com/9392655/231204340-40c1bc31-1e1d-46d3-8a04-deb94924fd3e.png)

I have tried using different fonts, but the issue persists.

**Comment by cdelker** [comment]
Closed by f01098d
