### ISSUE TITLE
Height of \left( etc.

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#10]
The height of brackets calculated incorrectly when there are subscripts in the formula.

![Screenshot_20230414_105305](https://user-images.githubusercontent.com/9392655/231996223-e9a0f437-e4ad-4592-8edf-0b0ea4d0dbf1.jpg)

**Comment by cdelker** [comment]
Made some adjustments in 9e30ed2. Keeping open until I can do some more testing.

**Comment by pozitron57** [comment]
Now the vertical alignment is OK, but there is too little spacing before `\left` I would say.

![image](https://user-images.githubusercontent.com/9392655/233810505-0f1343d8-1bd5-48b9-bdbd-b0cc7f077873.png)

**Comment by cdelker** [comment]
More adjustments to fence spacing in a98e645.
