### ISSUE TITLE
\underline and \bar are too short

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#16]
<img width="189" alt="image" src="https://user-images.githubusercontent.com/9392655/233013404-251fca66-e05d-46cf-951d-2381494324d3.png">

![image](https://user-images.githubusercontent.com/9392655/233211759-f39aa65f-f932-44dc-af2c-a5ff5a5fe4dc.png)

**Comment by cdelker** [comment]
Same fundamental issue as #11 . Also applies to \overline and maybe others.

**Comment by cdelker** [comment]
b7b0884. `\bar` is still short, consistent with Mathjax, etc., but `\overline` fills the width.
