### ISSUE TITLE
superscripts and subscripts incorrectly applied to an empty element

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#17]
`^{235}_{92}\text{U}` or `{}^{235}_{92}\text{U}` produces very large bottom margin (as large as a few pages). And the positioning of indices is incorrect if ^ and _ are applied to an empty element.

<img width="271" alt="image" src="https://user-images.githubusercontent.com/9392655/233016790-34f1418d-ed49-41fa-bf72-ebfe8a457270.png">

Adding anything before ^ or _ fixes the problem:

<img width="249" alt="image" src="https://user-images.githubusercontent.com/9392655/233017019-2b81c818-00f8-4c54-ba23-0067a0479b72.png">

**Comment by pozitron57** [comment]
As a workaround I use `\overset{235}{_{92}}\text{U}`, works fine.

**Comment by cdelker** [comment]
Should be fixed by b08308a.
