### ISSUE TITLE
Add trigonometric functions tg and ctg (feature request)

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#18]
In some countries it is common to write tangent and cotangent as tg and ctg instead of tan and cot.

E.g. `\tg\alpha`, `\ctg\alpha`,` \arctg\alpha`, `\arcctg\alpha`. Mathjax doesn't know this, but latex knows.

**Comment by cdelker** [comment]
cad4c11 adds a `ziamath.declareoperator` method to define other functions/operators. And it defines the trig variants above automatically.
