### ISSUE TITLE
Incorrect spacing between variables and trigonometric functions

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#2]
I have encountered an issue with ziamath's handling of spacing between variables and trigonometric functions. When rendering an expression like $x\cos{\alpha}$, there is too little space between the variable $x$ and the function $\cos$, while there is too much space between the function $\cos$ and the angle $\alpha$. Ideally, there should be more space between $x$ and $\cos$, and less space between $\cos$ and $\alpha$. I have attached a screenshot to illustrate the issue.

![image](https://user-images.githubusercontent.com/9392655/231206815-fe45c8b2-e944-4ac3-a5fc-1a4e89f411c6.png)

This issue affects the readability of the rendered expressions. I would appreciate it if you could look into this problem and suggest a possible solution or fix. In the meantime, are there any temporary workarounds that I could implement to resolve the spacing issue?

Here is screenshot to illustrate how latex would render $x\cos{\alpha}$:
![image](https://user-images.githubusercontent.com/9392655/231207799-a8653d74-4e29-4167-bd43-f3b85fd3640e.png)

**Comment by cdelker** [comment]
You can manually add space using `\;`. But I agree it should do that automatically for trig functions, log, exp, etc.

**Comment by cdelker** [comment]
Closed by 11064f2.

**Comment by pozitron57** [comment]
`$\sin^2\alpha$` isn't good, compare ziamath:

![image](https://user-images.githubusercontent.com/9392655/232348763-5cbaf2b8-e986-47df-9f19-0955fac96a9d.png)

and latex:

![image](https://user-images.githubusercontent.com/9392655/232348768-30cfac07-033a-4603-a1b3-9b21018fe3a8.png)
