### ISSUE TITLE
Nested square roots

### ISSUE THREAD

**Issue by cdelker** [cdelker/ziamath#20]
Inconsistent height of nested square roots.
`\sqrt{1+\sqrt{1+\sqrt{1+\sqrt{1+\sqrt{1+x}}}}}`

![image](https://user-images.githubusercontent.com/44102190/233518452-037bae3c-ad47-4095-b747-ff915fcf973f.png)

This will require ability to "stretch" a glyph.

**Comment by pozitron57** [comment]
It is not only for nested roots. When the brackets are present inside the square root, the height of it is too high.

`\sqrt{\mu^2(m+M)^2 + (m-M)^2} \sqrt{\mu^2m+M^2 + m-M^2}`
![image](https://user-images.githubusercontent.com/9392655/233810998-90cdb2af-ecbd-4682-85d9-31bb2d94896d.png)

**Comment by cdelker** [comment]
edecc6f
