### ISSUE TITLE
Spacing before \frac

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#21]
(I've updated to https://github.com/cdelker/ziamath/commit/11064f2e9f573d539ba7c35dca540a259cb43f05)

`$p\dfrac{1}{2}p$`

<img width="128" alt="image" src="https://user-images.githubusercontent.com/9392655/233664260-12b6bfca-5ef3-4239-adb9-cc99323ff2b1.png">

**Comment by cdelker** [comment]
0c04c3b
