### ISSUE TITLE
\frac and \dfrac are the same size but different spacing

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#22]
```
$p = \dfrac{2}{3} nE$

$p = \frac{2}{3} nE$
```

<img width="291" alt="image" src="https://user-images.githubusercontent.com/9392655/233666386-3032de97-bb5c-422f-902c-902a70511891.png">

`\dfrac` should be larger than the `\frac`. Note that `\frac` has more space after the `=` sign.

(I've updated to https://github.com/cdelker/ziamath/commit/11064f2e9f573d539ba7c35dca540a259cb43f05)

**Comment by cdelker** [comment]
Fixed by 0c04c3b. This change adds the `inline` parameter to better control inline vs block (or text vs display) modes. Note that \frac will be the same size as \dfrac when inline=False, but \frac will be smaller when inline=True.

**Comment by pozitron57** [comment]
> Fixed by [0c04c3b](https://github.com/cdelker/ziamath/commit/0c04c3b0c5abce86d5b8c103d87b0357320fc46b). This change adds the `inline` parameter to better control inline vs block (or text vs display) modes. Note that \frac will be the same size as \dfrac when inline=False, but \frac will be smaller when inline=True.

How can I set this parameter?

**Comment by cdelker** [comment]
It's an argument to `ziamath.Latex` or `ziamath.Math.fromlatex`:

![image](https://user-images.githubusercontent.com/44102190/233847811-df8e8c7e-3a27-43d7-8a29-eb7ac9180675.png)

If you use `ziamath.Text`, inline/text mode math is delimited by single `$`, while block/display math delimited by double `$$`.

I may add a parameter to `ziamath.config` to set the style globally too. Still need to add this to the docs.
