### ISSUE TITLE
Align inside cases

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#27]
```
$
\begin{cases}
\dfrac{q}{C} = -L\dot{I_1} = -\dfrac{L}{3}\dot{I_2}\\
I_1 + I_2 = I = \dot{q} \Rightarrow \dot{I_1} + \dot{I_2} = \ddot{q}
\end{cases}
$
```

<img width="448" alt="image" src="https://user-images.githubusercontent.com/9392655/234313439-2bdf6640-5f3f-4e05-b924-622ef19699bd.png">

I am pretty much sure that both lines used to be left aligned recently. It should be aligned left by default I think.

Also, when aligning manually with `&`, space after `=` disappears.

```
$
\begin{cases}
\dfrac{q}{C} &= -L\dot{I_1} = -\dfrac{L}{3}\dot{I_2}\\
I_1 + I_2 = I &= \dot{q} \Rightarrow \dot{I_1} + \dot{I_2} = \ddot{q}
\end{cases}
$
```

<img width="485" alt="image" src="https://user-images.githubusercontent.com/9392655/234314559-9f4f0592-5559-471e-9076-48d293c43781.png">

**Comment by cdelker** [comment]
70785e3
