### ISSUE TITLE
decimal separator (feature request)

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#28]
In some countries, it is common to use a comma as a decimal separator. When using this format, both LaTeX and MathJax produce a large space after the comma. To avoid this spacing issue, the comma can be treated as a separator by using the following format: `$1{,}5$` (which also works in ziamath).

However, it would be more convenient to have a global parameter that considers all commas between digits as decimal separators. In LaTeX, I use the `siunitx` package to achieve this. (I have not found a way to do this globally in MathJax.)

**Comment by cdelker** [comment]
fc4db0b. Use `zm.config.decimal_separator = ','` to enable. Substitutes `,` with `{,}` when the comma is surrounded by digits.
