### ISSUE TITLE
dots are shifted left in \dddot{x} 

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#3]
![image](https://user-images.githubusercontent.com/9392655/231500045-6c4ecf7a-7671-468f-b8ac-5bd26e7816e4.png)

I am now trying to implement ziamath on my site and noticed quite a few bugs. I can create issues for everything I noticed if you are interested.

**Comment by cdelker** [comment]
Thanks for reporting these. Yes, keep submitting issues, as ziamath does need more testing. I'll look in to them soon.

**Comment by pozitron57** [comment]
Also I find that dots are too thin, it should be thicker.
![image](https://user-images.githubusercontent.com/9392655/232068536-fd6b3ab2-56b9-4606-b6e1-3b158d2fae01.png)

**Comment by cdelker** [comment]
Closed by 9441e86.
