### ISSUE TITLE
{,} gives too much spacing

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#31]
(Not sure whether it is related to https://github.com/cdelker/ziamath/issues/30)

After the latest commits `$x=1{,}5$` gives too much space around a comma (comma is meant as a decimal separator and it used to give less spacing).

![image](https://user-images.githubusercontent.com/9392655/235378130-ecc53eb2-3169-4b92-969b-0a5af9d223be.png)

**Comment by cdelker** [comment]
278c67f
