### ISSUE TITLE
Spacing: letter touches preceding subscript

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#33]
`$\omega^2_0A$`
![image](https://user-images.githubusercontent.com/9392655/235379373-42b1380c-c4a4-49d0-a67d-3e480ca81e17.png)

Latex for reference:
![image](https://user-images.githubusercontent.com/9392655/235379434-ba026b30-d508-41ed-b8d9-cf0481205e9c.png)

**Comment by cdelker** [comment]
278c67f
