### ISSUE TITLE
Brackets inside cases

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#35]
While `\begin{cases}...\end{cases}` works well if there are no brackets inside, it gives weird results if the brackets are present. Here is a couple of examples.

```
\begin{cases}
x(t)=5-t^2 \\
x(t) = x_0 + v_{0x}t + \dfrac{a_xt^2}{2} \\
v_x(t) = v_{0x} + a_xt  
\end{cases}
```
![image](https://user-images.githubusercontent.com/9392655/235469688-8c97afe3-5d33-4d3f-bac8-e05dc00f4de5.png)

```
\begin{cases}
\rho g L = \f_1 p_Н \\
\rho g (L+\ell) = \f_2 p_н
\end{cases}
```
![image](https://user-images.githubusercontent.com/9392655/235469950-0f6f388c-9c3b-40c7-a709-a3687518525e.png)

**Comment by cdelker** [comment]
278c67f
