### ISSUE TITLE
\prime applied to a letter with a subscript

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#36]
`$v'~v_1'~v'{}^2$` in ziamath (`'` should be over the subscript):
![image](https://user-images.githubusercontent.com/9392655/235624670-824866ae-c37d-4ab3-8dc1-015d190fc3b6.png)

and latex:
![image](https://user-images.githubusercontent.com/9392655/235624713-e3f7c6ef-f9aa-4b2e-8751-1ff8cd602f5b.png)

Also, `$v'^2$` gives an error in ziamath and renders OK with latex.

`$v'_1$` renders correctly with ziamath:
![image](https://user-images.githubusercontent.com/9392655/235626190-7d5e075e-6131-4f96-9e42-ccdbab86c115.png)

**Comment by cdelker** [comment]
This will need to be addressed in latex2mathml. Opened roniemartinez/latex2mathml#392.

**Comment by cdelker** [comment]
Fixed in latex2mathml.
