### ISSUE TITLE
Brackets () inside \left(...\right) 

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#37]
Inner brackets should not be the same height as \left(...\right)

`$\left( \dfrac{x^2}{y_1}(a-b)\right)$`

![Screenshot_20230502_150937](https://user-images.githubusercontent.com/9392655/235675846-13011f24-f8fd-40ca-afcd-a18c75b29ddf.jpg)

`$\left( \dfrac{x^2}{y_1} \left(a-b\right) \right)$` gives a good height for the inner pair of brackets.

**Comment by cdelker** [comment]
5d7e09f
