### ISSUE TITLE
| and \left|...\right| problems

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#38]
```
$|A| ~ |A_1| ~ |A^2|$

$\left|A\right| ~ \left|A_1\right| ~ \left|A^2\right|$
```

gives in ziamath:
![image](https://user-images.githubusercontent.com/9392655/235692219-594c966b-4fa7-4aa4-95ec-33fb3fb2cf4f.png)

1. Letter is too close to opening `|`
2. Spacing after the subscript is different for `|` and `\left|`.
3. `\left|...\right|` are too long when there is a superscript and the letter touches left `|`.

And in latex:
![image](https://user-images.githubusercontent.com/9392655/235692259-3deb13b0-20fd-49d4-aca5-1fb92af50ebd.png)

**Comment by cdelker** [comment]
dc41e5a
