### ISSUE TITLE
\dfrac in superscript is larger than elsewhere

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#39]
`\ddot{x} = -v_0 \dfrac{k}{m} e^{-\dfrac{kt}{m}}`

![image](https://user-images.githubusercontent.com/9392655/236341372-2f9ed7d5-b09a-4428-a8ba-32703f557bb4.png)

also, \tfrac and \frac have different size in superscript (not sure if it is intended).

**Comment by cdelker** [comment]
da31c21

\tfrac and \frac being different sizes wasn't really intended, but that's what Mathjax does too.
