### ISSUE TITLE
subscript and superscript size in nested fractions with minsizefraction

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#43]
Subscripts and superscripts are too big with `zm.config.minsizefraction = .6`.

`$\dfrac {\frac{x_1^2}{2}} {\frac{y_1}{2}} $`

![image](https://user-images.githubusercontent.com/9392655/236642566-efac3255-1e35-413c-b79d-c4a4db2f3731.png)

With default value of `minsizefraction` everything is OK
![image](https://user-images.githubusercontent.com/9392655/236642591-0236fb0a-ceef-4d97-aa3e-668c0c013b2f.png)

**Comment by cdelker** [comment]
This is the intended behavior. The font size will not go below minsizefraction * base font size, regardless of script level.
