### ISSUE TITLE
drawon() doesn't work properly (question)

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#47]
I am trying to use the following code to draw on the existing svg file.

``` python
import ziamath as zm
from xml.etree import ElementTree as ET
ET.register_namespace("", "http://www.w3.org/2000/svg")

with open('test.svg', 'r') as file:
    tree = ET.parse(file)
    root = tree.getroot()

    myequation = zm.Math.fromlatex(r'x+y', size=28)
    myequation.drawon(root, 100, 2)

    with open('test2.svg', 'wb') as output_file:
        tree.write(output_file, encoding='UTF-8')
```

The output file is saved, but `x`, `+` and `y` are on the same place: 
![image](https://github.com/cdelker/ziamath/assets/9392655/9b097d87-bb22-4159-99fd-0ea6621c7e08)

Size and coordinates doesn't have any effect. What I may be doing wrong?

**Comment by cdelker** [comment]
Did you try `zm.config.svg2 = False`? It's likely whatever app you're using to view the output doesn't support SVG2.0 commands `<symbol>` and `<use>`, which means characters won't be translated to the correct location.

**Comment by pozitron57** [comment]
Thanks, it works.
