### ISSUE TITLE
\dddot{x} spacing

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#48]
```
~ ~\dot{x} \\
~ ~\ddot{x} \\
~ ~\dddot{x}
```

![image](https://github.com/cdelker/ziamath/assets/9392655/c4e00b79-d6da-4edb-9908-638f43d495c8)

\dot and \ddot work well, but \dddot shifts left too much. I believe it used to be OK.

**Comment by cdelker** [comment]
8a723fa
