### ISSUE TITLE
Greek and cyrillic letters are not italic in math mode

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#49]
1. Greek `\alpha \beta \gamma \delta \mu`

Ziamath:
![image](https://github.com/cdelker/ziamath/assets/9392655/c89f548e-a1fd-4d84-a478-568cbb56845f)

Xelatex with XITS2 font:
![image](https://github.com/cdelker/ziamath/assets/9392655/7d980982-024e-4974-8ff8-982ae1dd7e56)

2. Cyrillic
```
F_{где}~
F_\text{где}~
F_\textit{где}
```

Ziamath:
![image](https://github.com/cdelker/ziamath/assets/9392655/ed83d97d-3900-4a0d-b58f-f34285de1d66)

Xelatex:
![image](https://github.com/cdelker/ziamath/assets/9392655/2d31b568-ed91-40e3-9b58-496315fff6f1)

I like that Cyrillic letters are rendered in Ziamath upright, because they are mainly used for subscripts and measurements units, and normally should not be italic. However, it seems that currently it is not possible at all to get italics for Cyrillics.

**Comment by cdelker** [comment]
8a723fa
