### ISSUE TITLE
Fraction bar alignment

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#51]
```
\dfrac{M}{m} = 
\left(\dfrac{h}{R}\right)^{\kern-0.2em 2}
\cdot
\dfrac{1}{3-\tfrac{2R}{h}}
```

Ziamath (the bar over `R` is too low; fraction bar in `2R/h` is not aligned with minus sign):
![image](https://github.com/cdelker/ziamath/assets/9392655/dab50bb8-4d50-4868-9b18-7ed0850c04a0)

Xelatex:
![image](https://github.com/cdelker/ziamath/assets/9392655/aa223514-0d32-4315-9b6c-a3d8ed120bde)

Also I would say that in Xelatex version `\tfrac` size looks better.

**Comment by cdelker** [comment]
e9feab8
