### ISSUE TITLE
slash spacing is too large

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#52]
`h/R`

Ziamath:
![image](https://github.com/cdelker/ziamath/assets/9392655/f65126ed-28cd-4fa2-9563-af940d7e7ac9)

Xelatex:
![image](https://github.com/cdelker/ziamath/assets/9392655/841f003b-f9d3-460a-a047-db1eb6c3aea2)

**Comment by cdelker** [comment]
161e832 reduces spacing to 0em. This is another exception to the MathML Operators Dictionary, in addition to zero spacing around |.
