### ISSUE TITLE
Capital Greek letters should not be italic

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#53]
`$\Delta x ~ \Omega$`

Ziamath:
![image](https://github.com/cdelker/ziamath/assets/9392655/fe5889b2-896a-4f06-a9ba-de461fd1da69)

Xelatex:
![image](https://github.com/cdelker/ziamath/assets/9392655/1b70146a-8a46-420b-be60-0fbd4616f06b)

Interesting. I didn't know that small Greek letters in math mode should be italic and capital ones shouldn't.

**Comment by cdelker** [comment]
e84911c. I didn't know that either... Note the italic variant can still be obtained with `\mathit{\Delta}`.
