### ISSUE TITLE
Different vertical alignment for subscripts

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#54]
`$\alpha_1 \beta_1 \varphi_1 \gamma_1 \delta_1 \omega_1$`

Ziamath:
![image](https://github.com/cdelker/ziamath/assets/9392655/0fb8a82c-d635-4ffc-9ba4-cc2175ca4edd)

Xelatex:
![image](https://github.com/cdelker/ziamath/assets/9392655/e389d366-0156-46bd-b9c4-c3ac5ae24eba)

**Comment by cdelker** [comment]
f431b2e
