### ISSUE TITLE
Fraction bar in \tfrac is too thin

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#55]
`\dfrac{1-\tfrac{a+b}{c+d}}{2}`

Ziamath:
![image](https://github.com/cdelker/ziamath/assets/9392655/3afb25eb-c9ff-43de-95ef-a9731495cc3e)

Xelatex:
![image](https://github.com/cdelker/ziamath/assets/9392655/17a87da7-7e49-4d3d-aa25-b0ed864346c5)

Latex uses the same thickness for \dfrac and \tfrac bars, which is the same as the thickness of a minus sign. The same applies to `+` and `­–` signs.

**Comment by cdelker** [comment]
5977633
