### ISSUE TITLE
| | spacing is still too large

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#56]
You already adressed it in https://github.com/cdelker/ziamath/issues/38 but the spacing still differs from latex.

`|x+2| \\ |A|`

Ziamath:
![image](https://github.com/cdelker/ziamath/assets/9392655/138d0584-3cd3-453f-b5ba-9deee88024c8)

Xelatex:
![image](https://github.com/cdelker/ziamath/assets/9392655/ab7e4ab0-124c-4895-8bb8-d9709548ed79)

**Comment by cdelker** [comment]
0a487be
