### ISSUE TITLE
slash is too large in \left(...\right)

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#57]
`\left(1-1/b\right) \\ (1-1/b)`

Ziamath:
![image](https://github.com/cdelker/ziamath/assets/9392655/6a1db0f8-a914-42b6-ae96-a9b8220e76e5)

Xelatex:
![image](https://github.com/cdelker/ziamath/assets/9392655/54ae8fea-59e4-473c-9ad0-1cf96b648170)

**Comment by cdelker** [comment]
bb7a6ef
