### ISSUE TITLE
\dfrac arguments without curly braces

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#6]
Commands `\dfrac 3 2 1` and `\dfrac 32 1` in latex produce the same result (like the first one in the screenshot).

![Screenshot_20230413_153752](https://user-images.githubusercontent.com/9392655/231777183-ce339cbc-c024-46c7-ba34-1ebf755cdcc2.jpg)

**Comment by cdelker** [comment]
Fixed by https://github.com/roniemartinez/latex2mathml/issues/386
