### ISSUE TITLE
Module spacing

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#63]
It has been addressed in https://github.com/cdelker/ziamath/issues/9, but it isn't perfect for now.

`|F| = m|a| = m\left|\dfrac{v-v_0}{\Delta t}\right|`

Ziamath:
![image](https://github.com/cdelker/ziamath/assets/9392655/aaddcb9f-14de-415b-9580-d438a2c6d254)

Xelatex:
![image](https://github.com/cdelker/ziamath/assets/9392655/9b609af9-82dc-4252-b9c2-824bf22c80b8)

For single letters, spacing is too large. For the fraction, the spacing is different for left and right pipes.

**Comment by cdelker** [comment]
0a487be
