### ISSUE TITLE
$mu$ (also em, pt etc.) are rendered regular

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#64]
$2mv=3mu$

![image](https://github.com/cdelker/ziamath/assets/9392655/f5458bdc-0b72-4685-b0bb-545384f4e036)

If the formula contains a string that coincides with a measurement unit (such as mu, em, pt), it renders regular.

**Comment by cdelker** [comment]
da056da applies a hack to latex2mathml's code to disable units.
