### ISSUE TITLE
Impossible to use em, ex, cm etc. units with kern, hspace etc.

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#65]
After https://github.com/cdelker/ziamath/issues/64,

`$^{\kern-0.4em 2}$` renders as text
![image](https://github.com/cdelker/ziamath/assets/9392655/b6a6a5d1-b134-4138-ac08-27436f275ebe)

I used it to add some negative space.

In fact, nothing containing units doesn't work (such as \hspace{1cm} etc.)

**Comment by cdelker** [comment]
d2e9add restores parsing of units while still applying italics per #64.
