### ISSUE TITLE
\frac i2 and \frac 32 behaves differently

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#68]
``` latex
$U=\dfrac 32 \nu RT$

$U=\dfrac i2 \nu RT$
```

![image](https://github.com/cdelker/ziamath/assets/9392655/d5d5e564-a170-4bb1-ac0d-dc1f434b2dcb)

If the first symbol is a digit it works incorrectly. OK if it's a letter.

Related to https://github.com/cdelker/ziamath/issues/6

**Comment by cdelker** [comment]
Fixed in 0.9.
