### ISSUE TITLE
\text{--} in math mode should give en-dash

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#69]
``` latex
$ a\text{-}b $

$ a\text{--}b $

$ a\text{---}b $
```
Ziamath:
![image](https://github.com/cdelker/ziamath/assets/9392655/0fc5c016-bc5d-4b78-851f-f8c0efb1548c)

Xelatex converts double hyphen to en-dash and 3 hyphens to em-dash:
![image](https://github.com/cdelker/ziamath/assets/9392655/0966f3f7-9906-459d-b1ed-136f791738b4)

The same applies to `$ a\mbox{--} b $` etc.

**Comment by cdelker** [comment]
55e129b
