### ISSUE TITLE
x' should be rendered as x\prime, not x^\prime

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#7]
![image](https://user-images.githubusercontent.com/9392655/231806716-3b53e983-1aaf-4c6f-b737-76e70fde2fd4.png)

**Comment by cdelker** [comment]
Ugh, this behavior is font-dependent. `x'` should translate into `x^\prime`, but some fonts define the `\prime` glyph to be a big symbol, and some define it as already in the superscript position.

Asana Math uses the "big prime" glyph, so it looks ok:
![image](https://user-images.githubusercontent.com/44102190/232333593-e3a13ff6-cc13-44d8-91b5-26fa3f724bfb.png)

But Libertinus Math uses a pre-superscripted prime glyph, so it gets shifted up twice:
![image](https://user-images.githubusercontent.com/44102190/232333631-4c791cd1-49cc-4a72-b2bf-62c5ed274107.png)

**Comment by cdelker** [comment]
5a35335 checks the size of the font's prime glyph to adjust between \prime and ^\prime. Also for similar glyphs such as \dprime.

**Comment by cdelker** [comment]
Really fixed by e3a42c0 which uses the font's ssty GSUB feature to pick an appropriate prime glyph.
