### ISSUE TITLE
\sin^2\alpha spacing

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#73]
`$\sin^2\alpha$` gives in Xelatex:
![image](https://github.com/cdelker/ziamath/assets/9392655/8f920e1d-f083-4c07-add6-d496a3db1096)

And in Ziamath:
![image](https://github.com/cdelker/ziamath/assets/9392655/9582a701-c9f5-4bc8-b09b-51cddd789d40)

Note the spacing after the power, it is much larger in latex.
(Personally I would like spacing to be something in between these two cases.)

**Comment by cdelker** [comment]
Fixed in 0.9.
