### ISSUE TITLE
Specify output path

### ISSUE THREAD

**Issue by GrimPixel** [cdelker/ziamath#74]
How could the user specify a path and export SVG there?

**Comment by cdelker** [comment]
The `.svg()` method will get the SVG data as a string, so it can be written to a file:

```python
eqn = zm.Latex(r'\sqrt{a+b}')
with open('equation.svg', 'w') as f:
    f.write(eqn.svg())
```

**Comment by GrimPixel** [comment]
Thank you for the explanation.
