### ISSUE TITLE
\text{\bf ...} doesn't work

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#75]
I wasn't able to get bold brackets in math mode. Is it possible?

`$q(t) \bf{q(t)} \text{\bf q(t)}$` in latex:
<img width="645" alt="image" src="https://github.com/cdelker/ziamath/assets/9392655/0f4d4f81-c043-471b-82b2-1c088c253cf0">

In Ziamath:
<img width="707" alt="image" src="https://github.com/cdelker/ziamath/assets/9392655/491014c7-a86a-49ae-b7de-1527587fde9c">

**Comment by cdelker** [comment]
Using `\textbf` does the trick: `$q(t) \bf{q(t)} \textbf{q(t)}$`.

Similarly, `\textit` for italic text mode.
