### ISSUE TITLE
The index of the cube root is positioned too high above the radical symbol

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#76]
`$R = \sqrt[3]{\dfrac{gr^2T^2}{4\uppi^2}}$`

Xelatex:

<img width="522" alt="image" src="https://github.com/cdelker/ziamath/assets/9392655/bd5f5356-1667-4046-92da-a7adfa804b6b">

Ziamath:

<img width="397" alt="image" src="https://github.com/cdelker/ziamath/assets/9392655/2636e3b0-bacc-4d8f-b1a1-51b101078629">

**Comment by cdelker** [comment]
Related: https://github.com/stipub/stixfonts/issues/206

Looks like there's two interpretations for vertical positioning of the radical degree. The OpenType font specification works better for regular-height radicals, but MathML specification works better with extended height radicals. Until this is cleared up, Ziamath could switch between the two depending on the height of the radical, and would work well at least for Stix fonts.

**Comment by pozitron57** [comment]
I find that in the current implementation (version 0.10) the index is too small. See comparison with Xelatex:

<img width="251" alt="image" src="https://github.com/cdelker/ziamath/assets/9392655/49417d6e-a15c-4409-a186-64aee22462fb">
