### ISSUE TITLE
\kern0pt shifts text while it shouldn't

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#79]
```latex
\left(\dfrac Mm - 1\right) \\ 
\left(\kern0pt\dfrac Mm - 1\right) \\
\left(\kern1pt\dfrac Mm - 1\right)
```

Ziamath:
<img width="436" alt="image" src="https://github.com/user-attachments/assets/681c9cae-192e-453c-81ae-c2bc9ad5af74">

Xelatex:
<img width="476" alt="image" src="https://github.com/user-attachments/assets/4eaec365-3bc5-43f0-9273-54c648ca9abc">

Also height of the brackets is a bit different in Ziamath and Latex, but I find both variants satisfactory.

**Comment by cdelker** [comment]
Cannot reproduce this one. Perhaps it was "accidentally" fixed in another commit?

**Comment by pozitron57** [comment]
Neither can I reproduce this in 0.11. Thanks.
