### ISSUE TITLE
\uparrow height

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#80]
`\uparrow`, `\downarrow` has the height of the line (version 0.11).

`$v=\sqrt{\dfrac{GM}{r\downarrow}} \Rightarrow v \uparrow$`

XeLaTeX:

<img width="644" alt="image" src="https://github.com/user-attachments/assets/6c7f8427-8ba2-4ddb-b685-528ccba0602c">

Ziamath:

<img width="661" alt="image" src="https://github.com/user-attachments/assets/dd7fbc04-0ba2-4e8b-8c9f-07db6566aa3b">

**Comment by pozitron57** [comment]
Probably the same issue:

`$\langle u \rangle = \sqrt{\dfrac{\langle u_1 \rangle^2+\langle u_2 \rangle^2}{2}}$`

<img width="235" alt="image" src="https://github.com/user-attachments/assets/c1eb0eab-91e5-49c4-827f-db1ebc94d9d7">

**Comment by cdelker** [comment]
Fixed by 05eccf9b926c66f3c684a5dce5e86d92d629f6a4. Note to get "stretchy" angle brackets, use `\left\langle` and `\right\rangle`.
