### ISSUE TITLE
Prime is superscript

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#81]
I run again into https://github.com/cdelker/ziamath/issues/7 (version 0.11)

**Comment by cdelker** [comment]
Fixed in 616c1a245abcf38cdbf72b9791b92aa03b9f8c91. Occurred only when adding text to any equation using the same font - switching the font to "dflt" then back to "math" language didn't restore the "ssty" feature that substitutes the appropriate prime glyphs.
