### ISSUE TITLE
 $pV\uparrow$

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#83]
`$pV\uparrow$` gives an error 'float division by zero', 
while `$kV\uparrow$` renders just fine.
Version 0.11

**Comment by pozitron57** [comment]
Another example giving the same error: `$F_1\uparrow$`

**Comment by cdelker** [comment]
Fixed by ebf39a182e8cee4702f5485418f2bc1aa790c70a. Occurred when line height extended below the baseline (e.g. with a "p", but not with a "k".)
