### ISSUE TITLE
librsvg does not render svg generated from ziamath correctly

### ISSUE THREAD

**Issue by linwaytin** [cdelker/ziamath#85]
I found this problem on Emacs. Emacs uses [librsvg](https://github.com/GNOME/librsvg) for svg rendering, so I also try another program, [imv](https://sr.ht/~exec64/imv/), which also uses librsvg. The issue is that librsvg has trouble to show content in the svg files generated from ziamath. Most time I see nothing (a blank canvas). 

Does the generated svg contain some non-standard code? Or the problem is from librsvg?

I like this package and hopefully can use it more. Thank you.

**Comment by linwaytin** [comment]
I test it on a few other rendering engines. 
Firefox: Ok
Inkscape: Ok
resvg: Wrong, similar to librsvg.

**Comment by cdelker** [comment]
Did you try [turning off SVG2.0](https://ziamath.readthedocs.io/en/latest/options.html#svg-version-compatibility)?

`zm.config.svg2 = False`

Some SVG renderers aren't compatible with the still draft SVG 2.0 specification, so this may help.

**Comment by linwaytin** [comment]
Ok, that works like a charm....
Quite surprising, at least resvg [claims](https://github.com/linebender/resvg#svg-support) that it has pretty good SVG2 support. 

Thanks a lot. Great package!

**Comment by cdelker** [comment]
I looked into it a bit more, and found there must be a difference in how some renderers interpret the <symbol> element when it has both a viewBox and a width/height attribute. Commit cdelker/ziafont@b1efaf1b97b8ed3453e390995560482666b57ffd in the Ziafont dependency should take care of it so you don't have to turn off the SVG2 flag.

**Comment by linwaytin** [comment]
Thanks. That is awesome!
