### ISSUE TITLE
spacing inside module depends on other symbols

### ISSUE THREAD

**Issue by pozitron57** [cdelker/ziamath#9]
Spacing would be ok with single |e| only.

![Screenshot_20230413_202113](https://user-images.githubusercontent.com/9392655/231849348-f04ffccc-7181-406d-bc61-bf67e5ea68df.jpg)

Though `\left| ... \right|` always produces correct output.

**Comment by cdelker** [comment]
94bd930 removes spaces around all |, whether an operator or a fence. This seems consistent with Mathjax.
